### ISSUE TITLE
Unable to start application

### ISSUE THREAD

**Issue by schiller-manuel** [CodyJasonBennett/r3f-native-starter#2]
I tried to start this app but I get this error message, do you have an idea what's wrong in my setup?

```
TypeError: undefined is not an object (evaluating '_expoModulesCore.NativeModulesProxy.ExpoUpdates')
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/react-native/Libraries/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:290747:3 in global code

Unable to start your application. Please refer to https://expo.fyi/no-registered-application for more information.
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:200:6 in runApplication
```

I tried running on iOS and Android, but both fail with the above error.

**Comment by CodyJasonBennett** [comment]
Does your configuration match this repo? Maybe try reinstalling deps (and remove your lockfile) to ensure everything exists and work from there.

**Comment by CodyJasonBennett** [comment]
I'm seeing this after updating the Expo app. I've updated the local/R3F build deps, maybe try that out to see if that clears things up.

**Comment by schiller-manuel** [comment]
Thanks, it works now :)
Really looking forward for https://github.com/pmndrs/react-three-fiber/pull/1699 to be merged.
